source 'https://rubygems.org'
gem 'sinatra'
gem 'line-bot-api'
gem "sinatra-activerecord"
gem "rake"
gem 'pg'
gem 'nokogiri'
gem 'bitly'
gem 'capybara'
gem 'selenium-webdriver'
gem 'wikipedia-client'
